<h3>Workshop 15</h3>

<!--<script>-->
<!--    let xhr = new XMLHttpRequest();-->
<!---->
<!---->
<!--    // Track the state changes of the request.-->
<!--    xhr.onreadystatechange = function () {-->
<!--        const DONE = 4; // readyState 4 means the request is done.-->
<!--        const OK = 200; // status 200 is a successful return.-->
<!--        if (xhr.readyState === DONE)-->
<!--        {-->
<!--            if (xhr.status === OK) {-->
<!--                console.log(xhr.responseText); // 'This is the output.'-->
<!--            }-->
<!--            else-->
<!--            {-->
<!--                console.log('Error: ' + xhr.status);-->
<!--                // An error occurred during the request.-->
<!--            }-->
<!--        }-->
<!--    };-->
<!---->
<!---->
<!--    xhr.open('GET', 'send-ajax-data.php');-->
<!---->
<!---->
<!--    // Send the request to send-ajax-data.php-->
<!--   //  xhr.send(null);-->
<!---->
<!--</script>-->

<button id="goButton">Press me</button><p style="border : 1px solid blue; " id="output">Output</p>

<body>

    <p><strong>Start typing a name in the input field below:</strong></p>

    <form>
        First name: <input type="text" onkeyup="showHint(this.value)">
    </form>

    <p>Suggestions: <span id="txtHint"></span></p>

    <select id="resultsSelectionBox"></select>

    <br>
    <p><strong>LIVE SEARCH: type a name in the input field below:</strong></p>

    <form>
        <div>
            First name: <input type="text" onkeyup="showHint2(this.value)">
            <p><span id="txtHint2"></span></p>
            <div id="resultsSelectionBox2" ></div>
        </div>
    </form>

<!--    <select id="resultsSelectionBox2"></select>-->

</body>

<div>
    <script src="Views/test.js" type="text/javascript" charset="utf-8"></script>
</div>